from csv_detective.parsing.text import _process_text

proportion = 0.55
tags = ["fr", "geo"]
labels = [
    "adresse",
    "localisation",
    "adresse postale",
    "adresse geographique",
    "adr",
    "adresse complete",
    "adresse station",
]

voies = {
    "aire ",
    "allee ",
    "avenue ",
    "base ",
    "boulevard ",
    "cami ",
    "carrefour ",
    "chemin ",
    "cheminement ",
    "chaussee ",
    "cite ",
    "clos ",
    "coin ",
    "corniche ",
    "cote ",
    "cour ",
    "cours ",
    "domaine ",
    "descente ",
    "ecart ",
    "esplanade ",
    "faubourg ",
    "gare ",
    "grande rue",
    "hameau ",
    "halle ",
    "ilot ",
    "impasse ",
    "lieu dit",
    "lotissement ",
    "marche ",
    "montee ",
    "parc ",
    "passage ",
    "place ",
    "plan ",
    "plaine ",
    "plateau ",
    "pont ",
    "port ",
    "promenade ",
    "parvis ",
    "quartier ",
    "quai ",
    "residence ",
    "ruelle ",
    "rocade ",
    "rond point",
    "route ",
    "rue ",
    # 'sente - sentier',
    "square ",
    "tour ",
    # 'terre-plein',
    "traverse ",
    "villa ",
    "village ",
    "voie ",
    "zone artisanale",
    "zone d’amenagement concerte",
    "zone d’amenagement differe",
    "zone industrielle",
    "zone ",
    # 'r',
    "av ",
    "pl ",
    "bd ",
    "cami ",
    # 'che',
    "chs ",
    "dom ",
    "ham ",
    "ld ",
    # 'pro',
    # 'rte',
    "vlge ",
    "za ",
    "zac ",
    "zad ",
    "zi ",
    # 'car',
    "fg ",
    # 'lot',
    "imp ",
    # 'qu',
    "mte",
}


def _is(val):
    """Repere des adresses"""
    if not isinstance(val, str) or len(val) > 150:
        return False
    val = _process_text(val)
    return any(x in val for x in voies)


_test_values = {
    True: ["rue du martyr"],
    False: ["un batiment"],
}
